In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Data Loading & Cleaning (Pandas & NumPy)
Read the dataset

In [2]:
df = pd.read_csv("samsung_global_sales_dataset.csv")
df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,ARS,907.0,1130820.39,E-commerce Platform,Samsung Pay,Business,45–54,NaN,3.2,Kept
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,ARS,907.0,1322152.04,Authorized Reseller,Net Banking,Government,55+,Feature Phone,NaN,Kept
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,ARS,907.0,1964398.74,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,ARS,907.0,660359.49,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,NaN,4.0,Kept
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,ARS,907.0,2835245.72,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept

2. Display the shape, info, and statistical summary

In [3]:
df.shape

(15500, 28)

In [4]:
df.info()
#df["storage"]

<class 'pandas.DataFrame'>
RangeIndex: 15500 entries, 0 to 15499
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 15500 non-null  str
 1   sale_date               15500 non-null  str
 2   year                    15500 non-null  int64
 3   quarter                 15500 non-null  str
 4   month                   15500 non-null  str
 5   country                 15500 non-null  str
 6   region                  15500 non-null  str
 7   city                    15500 non-null  str
 8   product_name            15500 non-null  str
 9   category                15500 non-null  str
 10  storage                 7651 non-null   str
 11  color                   15500 non-null  str
 12  is_5g                   15500 non-null  str
 13  unit_price_usd          15500 non-null  float64
 14  discount_pct            15500 non-null  int64
 15  units_sold              15500 non-null  int64
 16  discounted_price_usd    15500 non-null  float64
 17  revenue_usd             15500 non-null  float64
 18  currency                15500 non-null  str
 19  fx_rate_to_usd          15500 non-null  float64
 20  revenue_local_currency  15500 non-null  float64
 21  sales_channel           15500 non-null  str
 22  payment_method          15500 non-null  str
 23  customer_segment        15500 non-null  str
 24  customer_age_group      15500 non-null  str
 25  previous_device_os      6127 non-null   str
 26  customer_rating         11249 non-null  float64
 27  return_status           15500 non-null  str
dtypes: float64(6), int64(3), str(19)
memory usage: 3.3 MB

In [5]:
df.describe()

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
count,15500.000000,15500.000000,15500.000000,15500.000000,15500.000000,15500.000000,15500.000000,1.550000e+04,11249.000000
mean,2022.511935,665.116825,5.708452,2.360000,627.134001,1478.145734,1054.528710,1.595853e+06,3.743515
std,1.113496,736.014360,6.406814,1.897958,695.723305,2368.688098,4062.232887,1.092157e+07,0.721258
min,2021.000000,8.200000,0.000000,1.000000,6.600000,6.610000,0.790000,6.080000e+00,2.500000
25%,2022.000000,185.435000,0.000000,1.000000,172.780000,254.265000,1.360000,1.199072e+03,3.100000
50%,2023.000000,421.490000,3.000000,2.000000,397.410000,739.380000,10.650000,7.813940e+03,3.700000
75%,2024.000000,938.657500,10.000000,3.000000,882.907500,1695.315000,110.000000,9.126992e+04,4.400000
max,2024.000000,5442.700000,20.000000,10.000000,5442.700000,47665.900000,24500.000000,3.647727e+08,5.000000

3. Identify missing values

In [17]:
df.isnull().sum()

sale_id                      0
sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   7849
color                        0
is_5g                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os           0
customer_rating              0
return_status                0
dtype: int64

In [ ]:
df["customer_rating"] = df["customer_rating"].fillna(df["customer_rating"].median())
df["customer_rating"].isnull().sum()

np.int64(0)

In [14]:
df.head(20)

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,ARS,907.0,1130820.39,E-commerce Platform,Samsung Pay,Business,45–54,Android (Samsung),3.2,Kept
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,ARS,907.0,1322152.04,Authorized Reseller,Net Banking,Government,55+,Feature Phone,3.7,Kept
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,ARS,907.0,1964398.74,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,ARS,907.0,660359.49,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,Android (Samsung),4.0,Kept
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,ARS,907.0,2835245.72,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept
5,SAMS-00000006,2021-09-15,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Watch 5,Galaxy Watch,...,ARS,907.0,371343.94,E-commerce Platform,Net Banking,Government,25–34,Android (Samsung),2.6,Kept
6,SAMS-00000007,2021-11-02,2021,Q4,November,Argentina,South America,Buenos Aires,Samsung 870 EVO 1TB SSD,Accessories,...,ARS,907.0,376078.48,Carrier Store,Net Banking,Enterprise,55+,Android (Samsung),4.5,Kept
7,SAMS-00000008,2022-01-26,2022,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy M14 5G,Galaxy M,...,ARS,907.0,315218.78,Third-Party Retailer,Debit Card,Education,25–34,Feature Phone,3.7,Kept
8,SAMS-00000009,2022-02-22,2022,Q1,February,Argentina,South America,Buenos Aires,Samsung Galaxy Buds Live,Galaxy Buds,...,ARS,907.0,143215.30,Online (Samsung.com),EMI / Installment,Individual,18–24,Android (Samsung),3.7,Kept
9,SAMS-00000010,2022-02-28,2022,Q1,February,Argentina,South America,Buenos Aires,Samsung Galaxy A53 5G,Galaxy A,...,ARS,907.0,1168125.30,Third-Party Retailer,Net Banking,Government,25–34,Android (Other),4.7,Kept
10,SAMS-00000011,2022-06-17,2022,Q2,June,Argentina,South America,Buenos Aires,Samsung Galaxy S22,Galaxy S,...,ARS,907.0,1764133.14,E-commerce Platform,Samsung Pay,Business,35–44,New User,3.7,Kept
11,SAMS-00000012,2022-06-29,2022,Q2,June,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9+,Galaxy Tab,...,ARS,907.0,2748210.00,Carrier Store,EMI / Installment,Enterprise,35–44,Android (Samsung),4.1,Kept
12,SAMS-00000013,2022-07-11,2022,Q3,July,Argentina,South America,Buenos Aires,Samsung 11kg Washer-Dryer Combo,Appliances,...,ARS,907.0,989364.67,E-commerce Platform,Net Banking,Business,25–34,Android (Samsung),4.9,Kept
13,SAMS-00000014,2022-07-17,2022,Q3,July,Argentina,South America,Buenos Aires,Samsung Galaxy S22,Galaxy S,...,ARS,907.0,504464.33,Corporate / B2B,BNPL (Buy Now Pay Later),Government,25–34,New User,4.6,Kept
14,SAMS-00000015,2022-07-28,2022,Q3,July,Argentina,South America,Buenos Aires,Samsung Galaxy M14 5G,Galaxy M,...,ARS,907.0,145845.60,E-commerce Platform,Net Banking,Business,18–24,New User,4.3,Kept
15,SAMS-00000016,2022-08-06,2022,Q3,August,Argentina,South America,Buenos Aires,Samsung 32GB MicroSD Card,Accessories,...,ARS,907.0,35418.35,Carrier Store,Debit Card,Enterprise,35–44,Android (Samsung),3.0,Kept
16,SAMS-00000017,2022-09-27,2022,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy S24+,Galaxy S,...,ARS,907.0,5817334.74,Online (Samsung.com),Gift Card,Education,25–34,Android (Samsung),3.7,Kept
17,SAMS-00000018,2022-09-28,2022,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Buds Live,Galaxy Buds,...,ARS,907.0,644604.90,E-commerce Platform,Samsung Pay,Enterprise,35–44,Android (Samsung),3.7,Kept
18,SAMS-00000019,2022-12-19,2022,Q4,December,Argentina,South America,Buenos Aires,Samsung The Frame 55-inch,Smart TV,...,ARS,907.0,2319706.92,Corporate / B2B,Debit Card,Individual,18–24,Android (Samsung),4.7,Returned
19,SAMS-00000020,2022-12-21,2022,Q4,December,Argentina,South America,Buenos Aires,Samsung Galaxy S21 FE,Galaxy S,...,ARS,907.0,891018.66,Samsung Store,EMI / Installment,Government,18–24,New User,3.3,Kept

In [ ]:
df["previous_device_os"].astype('category')
df["previous_device_os"] = df["previous_device_os"].fillna(df["previous_device_os"].mode()[0])
df["previous_device_os"].isnull().sum()

0        Android (Samsung)
1            Feature Phone
2                 New User
3        Android (Samsung)
4          Android (Other)
               ...
15495    Android (Samsung)
15496    Android (Samsung)
15497    Android (Samsung)
15498    Android (Samsung)
15499                  iOS
Name: previous_device_os, Length: 15500, dtype: category
Categories (5, str): ['Android (Other)', 'Android (Samsung)', 'Feature Phone', 'New User', 'iOS']

In [ ]:
# product_storage = df.groupby("storage")[["product_name", "storage"]]
df["storage"] = df["storage"].fillna("0 B")
df["storage"].isnull().sum()

np.int64(0)